# Programming in R
# Coursera Rprog-0014
# Due May 17, 2015
#
## Programming Assignment 2: Caching the Inverse of a Matrix
##
## Instructions:
##
## *Matrix inversion* is usually a costly computation and there may be
## some benefit to caching the inverse of a matrix rather than compute
## it repeatedly (there are also alternatives to matrix inversion that
## we will not discuss here). Your assignment is to write a pair of
## functions that cache the inverse of a matrix.
#
## Write the following functions:
##
## makeCacheMatrix: This function creates a special "matrix" object
## that can cache its inverse.
##
## cacheSolve: This function computes the inverse of the special
## "matrix" returned by makeCacheMatrix above. If the inverse has
## already been calculated (and the matrix has not changed), then
## the cachesolve should retrieve the inverse from the cache.
##
## Computing the inverse of a square matrix can be done with the solve
## function in R. For example, if X is a square invertible matrix,
## then solve(X) returns its inverse.
##
## For this assignment, assume that the matrix supplied is always
## invertible.


## This function creates a special "matrix" object that can cache its
## inverse.


makeCacheMatrix <- function(x = matrix()) {
        cachedMatrix <- NULL
        y <- NULL


        # 'set' function sets the value of the passed matrix 'y' for
        # the rest of the functions to use as 'x'. It also removes any
        # existing values for 'cachedMatrix', which represents the
        # inverse matrix generated by setInverse
        set <- function(y) {
                x <<- y
                cachedMatrix <<- NULL
        }



        # 'get' function returns the value of the original matrix 'x'
        # which will be inverted to create 'cachedMatrix'
        get <- function(x) {
                x
        }



        # 'setInverse' function generates the inverse matrix
        # 'cachedMatrix' from the passed matrix 'x' and defines
        # 'cachedMatrix' in the global environment
        setInverse <- function(solve) {
                cachedMatrix <<- solve
                print(cachedMatrix)
        }



        # 'getInverse' function returns 'cachedMatrix', the cached
        # value generated by 'setInverse', if it exists
        getInverse <- function(x) {
                return(cachedMatrix)
        }



        return(list(set = set, get = get,
             setInverse = setInverse,
             getInverse = getInverse))

# end of function makeCacheMatrix
}



## This function computes the inverse of the special "matrix" returned
## by makeCacheMatrix above. If the inverse has already been
## calculated (and the matrix has not changed), then cacheSolve should
## retrieve the inverse from the cache.


cacheSolve <- function(x = matrix(), ...) {
        ## Return a matrix that is the inverse of 'x'

        # Call 'getInverse' from the makeCacheMatrix function, so
        # its current state can be evaluted
        cachedMatrix <- x$getInverse()

        # Check if inverse matrix 'cachedMatrix' exists. If it does,
        # print message to that effect, and return cached matrix.
        if(!is.null(cachedMatrix)) {
                print("Retrieving inverse matrix from cache")
                return(cachedMatrix)
        }

        # Inverse doesn't exist, so let's compute it. First, we'll
        # take the matrix available through 'get' in the formu
        dataForMatrix <- x$get()

        # then we'll calculate the inverse matrix using the R command
        # "solve" and store it in 'cachedMatrix'
        cachedMatrix <- solve(dataForMatrix, ...)
        x$setInverse(cachedMatrix)

        # Finally, we'll return a newly minted matrix
        return(cachedMatrix)

# end of function cacheSolve
}

# end of cachematrix.R

